apiVersion: v1
kind: ConfigMap
metadata:
  name: retail-config
data:
  DB_HOST: "mysql-service"
  DB_USER: "root"
  DB_PASSWORD: "rootpassword"
  DB_NAME: "capsule_db"
  DB_PORT: "3306"
  PORT: "3000"
  NODE_ENV: "production"
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: capsule-app
spec:
  replicas: 2

  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1

  selector:
    matchLabels:
      app: capsule-app
  template:
    metadata:
      labels:
        app: capsule-app
    spec:
      containers:
      - name: capsule-app
        image: lijazs/retail-devops-project:v1.0.0
        ports:
        - containerPort: 3000
        envFrom:
        - configMapRef:
            name: retail-config
        resources:
          limits:
            memory: "512Mi"
            cpu: "200m"
          requests:
            memory: "256Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: capsule-service
spec:
  selector:
    app: capsule-app
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
